server:
  port: 8088

#debug: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/av-service?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
  jooq:
    sql-dialect: MYSQL
   
logging:
  root: info
  level:
    org.study.self.jooq: DEBUG
    #org.jooq: DEBUG

management.security.enabled: false

user:
  img:
    width: 500
    height: 65
    save-path: F://img//
  account: guogenfang
  pwd: 123456
