/**
 * This class is generated by jOOQ
 */
package org.study.self.spring.boot.model;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * InnoDB free: 11264 kB
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -1142833325;

    private Integer id;
    private Integer roomId;
    private String  name;
    private Integer device;
    private Room room;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.roomId = value.roomId;
        this.name = value.name;
        this.device = value.device;
    }

    public User(
        Integer id,
        Integer roomId,
        String  name,
        Integer device
    ) {
        this.id = id;
        this.roomId = roomId;
        this.name = name;
        this.device = device;
    }

    public Integer getId() {
        return this.id;
    }

    public User setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getRoomId() {
        return this.roomId;
    }

    public User setRoomId(Integer roomId) {
        this.roomId = roomId;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public User setName(String name) {
        this.name = name;
        return this;
    }

    public Integer getDevice() {
        return this.device;
    }

    public User setDevice(Integer device) {
        this.device = device;
        return this;
    }
    
    /**
	 * @return the room
	 */
	public Room getRoom() {
		return room;
	}
	
	/**
	 * @param room the room to set
	 */
	public void setRoom(Room room) {
		this.room = room;
	}

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(roomId);
        sb.append(", ").append(name);
        sb.append(", ").append(device);
        sb.append(", ").append(room);

        sb.append(")");
        return sb.toString();
    }
}
