/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Test1 */

#ifndef _Included_jni_Test1
#define _Included_jni_Test1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Test1
 * Method:    hell
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_Test1_hell
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
