/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Native */

#ifndef _Included_jni_Native
#define _Included_jni_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Native
 * Method:    getMsg
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_Native_getMsg
  (JNIEnv *, jobject, jint);

/*
 * Class:     jni_Native
 * Method:    hasException
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_Native_hasException
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
