/**
 * This class is generated by jOOQ
 */
package org.study.self.jooq.model;

import java.io.Serializable;
import java.util.List;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InnoDB free: 4096 kB
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.8.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })

@Entity
@Table(name = "t_pl_room")
public class RoomModel implements Serializable {

	private static final long serialVersionUID = 1436570272;
		
	@Id
	private Integer id;
	
	@Column(name = "name")
	private String name;

//	 @OneToMany(cascade = {CascadeType.ALL})
//     @JoinColumn(name="roomId")
	private List<UserModel> users;

	public RoomModel() {
	}

	public RoomModel(RoomModel value) {
		this.id = value.id;
		this.name = value.name;
	}

	public RoomModel(Integer id, String name) {
		this.id = id;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public RoomModel setId(Integer id) {
		this.id = id;
		return this;
	}

	public String getName() {
		return this.name;
	}

	public RoomModel setName(String name) {
		this.name = name;
		return this;
	}

	public void setUsers(List<UserModel> users) {
		this.users = users;
	}
	
	public List<UserModel> getUsers() {
		return users;
	}

	@Override
	public String toString() {
		return "Room [id=" + id + ", name=" + name + ", users=" + users + "]";
	}
	
}
