/**
 * This class is generated by jOOQ
 */
package org.study.self.jooq.model;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InnoDB free: 4096 kB
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.8.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })

@Entity
@Table(name = "t_pl_user")
public class UserModel implements Serializable {

	private static final long serialVersionUID = 1092371851;

	@Id
	private Integer id;

	@Column(name="room_id")
	private Integer roomId;

	public UserModel() {
	}

	public UserModel(UserModel value) {
		this.id = value.id;
		this.roomId = value.roomId;
	}

	public UserModel(Integer id, Integer roomId) {
		this.id = id;
		this.roomId = roomId;
	}

	public Integer getId() {
		return this.id;
	}

	public UserModel setId(Integer id) {
		this.id = id;
		return this;
	}

	public Integer getRoomId() {
		return this.roomId;
	}

	public UserModel setRoomId(Integer roomId) {
		this.roomId = roomId;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("User (");

		sb.append(id);
		sb.append(", ").append(roomId);

		sb.append(")");
		return sb.toString();
	}
}
